quarkus:
  grpc:
    server:
      port: 9008
  http:
    port: 8089
  redisson:
    single-server-config:
      address: redis://192.168.48.130:6379
    threads: 16
    netty-threads: 32
    codec: org.redisson.codec.MarshallingCodec
  redis:
    hosts: 192.168.48.130

kernelapp:
  autoEnableDriversOnStartup: false
  autoEnablePeripheralDriversOnStartup: false
  saveModelOnTerminateModelling: false
  saveModelOnTerminateOperating: false
  updateRoutingTopologyOnPathLockChange: false
orderpool:
  sweepInterval: 60000
  sweepAge: 86400000
ssl:
  keystoreFile: ./config/keystore.p12
  truststoreFile: ./config/truststore.p12
  keystorePassword: password
  truststorePassword: password
defaultdispatcher:
  dismissUnroutableTransportOrders: true
  assignRedundantOrders: false
  rerouteTrigger: NONE
  reroutingImpossibleStrategy: IGNORE_PATH_LOCKS
  parkIdleVehicles: false
  considerParkingPositionPriorities: false
  reparkVehiclesToHigherPriorityPositions: false
  rechargeIdleVehicles: false
  keepRechargingUntilFullyCharged: true
  idleVehicleRedispatchingInterval: 10000
  orderPriorities: BY_DEADLINE
  orderCandidatePriorities: BY_DEADLINE
  vehiclePriorities: IDLE_FIRST,BY_ENERGY_LEVEL
  vehicleCandidatePriorities: IDLE_FIRST,BY_ENERGY_LEVEL
  deadlineAtRiskPeriod: 60000
defaultrouter:
  routeToCurrentPosition: false
  shortestpath:
    algorithm: DIJKSTRA
    edgeEvaluators: DISTANCE
  edgeevaluator:
    explicitproperties:
      defaultValue: 1000000
defaultperipheraljobdispatcher:
  idlePeripheralRedispatchingInterval: 10000
virtualvehicle:
  enable: true
  simulationTimeFactor: 1.0
  commandQueueCapacity: 2
  rechargeOperation: CHARGE
virtualperipheral:
  enable: true
statisticscollector:
  enable: true


rmikernelinterface:
  enable: true
  useSsl: false
  clientSweepInterval: 300000
  registryPort: 2099
  remoteKernelServicePortalPort: 55000
  remotePlantModelServicePort: 55001
  remoteTransportOrderServicePort: 55002
  remoteVehicleServicePort: 55003
  remoteNotificationServicePort: 55004
  remoteSchedulerServicePort: 55005
  remoteRouterServicePort: 55006
  remoteDispatcherServicePort: 55007
  remoteQueryServicePort: 55008
  remotePeripheralServicePort: 55009
  remotePeripheralJobServicePort: 55010
